package encryption

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

func resetCryptoForTest(t *testing.T) {
	t.Helper()
	t.Setenv("ENCRYPTION_KEY", "test-encryption-key-for-tests-only")
	ResetEncryptionKey()
	t.Cleanup(func() { ResetEncryptionKey() })
}

func TestEncryptDecrypt_RoundTrip(t *testing.T) {
	resetCryptoForTest(t)
	original := "hcloud-test-token-abc123xyz"
	encrypted, err := Encrypt(original)
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	if encrypted == original {
		t.Error("encrypted token should differ from plaintext")
	}

	decrypted, err := Decrypt(encrypted)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if decrypted != original {
		t.Errorf("expected %q, got %q", original, decrypted)
	}
}

func TestEncrypt_DifferentCiphertexts(t *testing.T) {
	resetCryptoForTest(t)
	token := "same-token"
	enc1, err := Encrypt(token)
	if err != nil {
		t.Fatal(err)
	}
	enc2, err := Encrypt(token)
	if err != nil {
		t.Fatal(err)
	}
	if enc1 == enc2 {
		t.Error("encrypting the same token twice should produce different ciphertexts (random nonce)")
	}
}

func TestDecrypt_InvalidData(t *testing.T) {
	resetCryptoForTest(t)
	_, err := Decrypt("not-valid-base64!!!")
	if err == nil {
		t.Error("expected error for invalid base64")
	}

	_, err = Decrypt("aGVsbG8=") // valid base64 but not valid ciphertext
	if err == nil {
		t.Error("expected error for invalid ciphertext")
	}
}

func TestAutoGeneratedKeyFile_CreatesAndReuses(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")

	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})
	ResetEncryptionKey()

	token := "my-secret-token"
	encrypted, err := Encrypt(token)
	if err != nil {
		t.Fatalf("first encrypt: %v", err)
	}

	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if len(data) != 64 {
		t.Fatalf("expected 64 hex chars, got %d", len(data))
	}
	if _, err := hex.DecodeString(string(data)); err != nil {
		t.Fatalf("key file is not valid hex: %v", err)
	}

	ResetEncryptionKey()

	decrypted, err := Decrypt(encrypted)
	if err != nil {
		t.Fatalf("decrypt after reset: %v", err)
	}
	if decrypted != token {
		t.Errorf("expected %q, got %q", token, decrypted)
	}
}

func TestEncryptDecryptField_RoundTrip(t *testing.T) {
	resetCryptoForTest(t)

	original := "sensitive data to encrypt"
	encrypted, err := EncryptField(original)
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	if encrypted == original {
		t.Error("encrypted should differ from plaintext")
	}

	decrypted, err := DecryptField(encrypted)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if decrypted != original {
		t.Errorf("expected %q, got %q", original, decrypted)
	}
}

func TestEncryptDecryptField_Empty(t *testing.T) {
	resetCryptoForTest(t)

	enc, err := EncryptField("")
	if err != nil {
		t.Fatalf("encrypt empty: %v", err)
	}
	if enc != "" {
		t.Errorf("expected empty, got %q", enc)
	}

	dec, err := DecryptField("")
	if err != nil {
		t.Fatalf("decrypt empty: %v", err)
	}
	if dec != "" {
		t.Errorf("expected empty, got %q", dec)
	}
}

func TestDecryptField_LegacyPlaintext(t *testing.T) {
	resetCryptoForTest(t)

	// Plain text that is not valid base64 should be returned as-is (legacy data).
	legacy := "this is plain text, not encrypted"
	result, err := DecryptField(legacy)
	if err != nil {
		t.Fatalf("unexpected error for legacy plaintext: %v", err)
	}
	if result != legacy {
		t.Errorf("expected %q, got %q", legacy, result)
	}
}

func TestDecryptField_CorruptedCiphertext(t *testing.T) {
	resetCryptoForTest(t)

	// Encrypt a value, then corrupt the ciphertext. Since it's still valid base64
	// with enough bytes, DecryptField should return an error (not silently fall back).
	encrypted, err := EncryptField("secret")
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}

	// Corrupt by flipping a character in the middle of the base64 string.
	corrupted := []byte(encrypted)
	mid := len(corrupted) / 2
	if corrupted[mid] == 'A' {
		corrupted[mid] = 'B'
	} else {
		corrupted[mid] = 'A'
	}

	_, err = DecryptField(string(corrupted))
	if err == nil {
		t.Error("expected error for corrupted ciphertext, got nil")
	}
}

func TestAutoGeneratedKeyFile_EnvVarTakesPrecedence(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	t.Setenv("ENCRYPTION_KEY", "env-var-key")
	ResetEncryptionKey()

	_, err := Encrypt("test")
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}

	if _, err := os.Stat(tmpKeyFile); !os.IsNotExist(err) {
		t.Error("key file should not be created when ENCRYPTION_KEY env var is set")
	}
}

func TestAutoGeneratedKeyFile_CorruptFileGeneratesNew(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	if err := os.WriteFile(tmpKeyFile, []byte("not-valid-hex"), 0600); err != nil {
		t.Fatal(err)
	}
	ResetEncryptionKey()

	_, err := Encrypt("test")
	if err != nil {
		t.Fatalf("encrypt with corrupt key file: %v", err)
	}

	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if len(data) != 64 {
		t.Fatalf("expected 64 hex chars after regeneration, got %d", len(data))
	}
}

func TestAutoGeneratedKeyFile_InvalidHex64Bytes(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	invalidHex := "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
	if err := os.WriteFile(tmpKeyFile, []byte(invalidHex), 0600); err != nil {
		t.Fatal(err)
	}
	ResetEncryptionKey()

	_, err := Encrypt("test")
	if err != nil {
		t.Fatalf("encrypt with invalid hex key file: %v", err)
	}

	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if len(data) != 64 {
		t.Fatalf("expected 64 hex chars after regeneration, got %d", len(data))
	}
	if _, err := hex.DecodeString(string(data)); err != nil {
		t.Fatalf("regenerated key file is not valid hex: %v", err)
	}
}

func TestAutoGeneratedKeyFile_PermissionCheckOnRead(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Unix file permissions not applicable on Windows")
	}

	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	ResetEncryptionKey()
	token := "permission-test-token"
	encrypted, err := Encrypt(token)
	if err != nil {
		t.Fatalf("initial encrypt: %v", err)
	}

	if err := os.Chmod(tmpKeyFile, 0644); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	ResetEncryptionKey()

	decrypted, err := Decrypt(encrypted)
	if err != nil {
		t.Fatalf("decrypt with loose permissions: %v", err)
	}
	if decrypted != token {
		t.Errorf("expected %q, got %q", token, decrypted)
	}

	info, err := os.Stat(tmpKeyFile)
	if err != nil {
		t.Fatalf("stat key file: %v", err)
	}
	perm := info.Mode().Perm()
	if perm != 0600 {
		t.Errorf("expected permissions 0600, got %04o", perm)
	}
}

func TestAutoGeneratedKeyFile_SymlinkRejected(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlink creation requires special privileges on Windows")
	}

	tmpDir := t.TempDir()
	realFile := filepath.Join(tmpDir, "real.key")
	symlinkPath := filepath.Join(tmpDir, ".encryption_key")

	if err := os.WriteFile(realFile, []byte("irrelevant"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(realFile, symlinkPath); err != nil {
		t.Fatal(err)
	}

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = symlinkPath
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})
	ResetEncryptionKey()

	_, err := Encrypt("test")
	if err == nil {
		t.Fatal("expected error when key file path is a symlink, got nil")
	}
}

func TestAutoGeneratedKeyFile_TrailingNewlineHandled(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	ResetEncryptionKey()
	token := "test-token"
	encrypted, err := Encrypt(token)
	if err != nil {
		t.Fatalf("initial encrypt: %v", err)
	}

	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if err := os.WriteFile(tmpKeyFile, append(data, '\n'), 0600); err != nil {
		t.Fatalf("write key file with newline: %v", err)
	}
	ResetEncryptionKey()

	decrypted, err := Decrypt(encrypted)
	if err != nil {
		t.Fatalf("decrypt after newline appended: %v", err)
	}
	if decrypted != token {
		t.Errorf("expected %q, got %q", token, decrypted)
	}
}
