package infra

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"testing"
)

func resetCryptoForTest(t *testing.T) {
	t.Helper()
	t.Setenv("ENCRYPTION_KEY", "test-encryption-key-for-tests-only")
	ResetEncryptionKey()
	t.Cleanup(func() { ResetEncryptionKey() })
}

func TestEncryptDecryptToken_RoundTrip(t *testing.T) {
	resetCryptoForTest(t)
	original := "hcloud-test-token-abc123xyz"
	encrypted, err := EncryptToken(original)
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	if encrypted == original {
		t.Error("encrypted token should differ from plaintext")
	}

	decrypted, err := DecryptToken(encrypted)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if decrypted != original {
		t.Errorf("expected %q, got %q", original, decrypted)
	}
}

func TestEncryptToken_DifferentCiphertexts(t *testing.T) {
	resetCryptoForTest(t)
	token := "same-token"
	enc1, err := EncryptToken(token)
	if err != nil {
		t.Fatal(err)
	}
	enc2, err := EncryptToken(token)
	if err != nil {
		t.Fatal(err)
	}
	if enc1 == enc2 {
		t.Error("encrypting the same token twice should produce different ciphertexts (random nonce)")
	}
}

func TestDecryptToken_InvalidData(t *testing.T) {
	resetCryptoForTest(t)
	_, err := DecryptToken("not-valid-base64!!!")
	if err == nil {
		t.Error("expected error for invalid base64")
	}

	_, err = DecryptToken("aGVsbG8=") // valid base64 but not valid ciphertext
	if err == nil {
		t.Error("expected error for invalid ciphertext")
	}
}

func TestAutoGeneratedKeyFile_CreatesAndReuses(t *testing.T) {
	// Use a temp directory for the key file.
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	// Clear env var so auto-generation kicks in.
	t.Setenv("ENCRYPTION_KEY", "")

	// Point to temp key file.
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})
	ResetEncryptionKey()

	// First call should auto-generate and write a key file.
	token := "my-secret-token"
	encrypted, err := EncryptToken(token)
	if err != nil {
		t.Fatalf("first encrypt: %v", err)
	}

	// Key file should exist and contain 64 hex chars.
	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if len(data) != 64 {
		t.Fatalf("expected 64 hex chars, got %d", len(data))
	}
	if _, err := hex.DecodeString(string(data)); err != nil {
		t.Fatalf("key file is not valid hex: %v", err)
	}

	// Reset and re-read — should reuse the same key from file.
	ResetEncryptionKey()

	decrypted, err := DecryptToken(encrypted)
	if err != nil {
		t.Fatalf("decrypt after reset: %v", err)
	}
	if decrypted != token {
		t.Errorf("expected %q, got %q", token, decrypted)
	}
}

func TestAutoGeneratedKeyFile_EnvVarTakesPrecedence(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	// Set env var — key file should NOT be created.
	t.Setenv("ENCRYPTION_KEY", "env-var-key")
	ResetEncryptionKey()

	_, err := EncryptToken("test")
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}

	if _, err := os.Stat(tmpKeyFile); !os.IsNotExist(err) {
		t.Error("key file should not be created when ENCRYPTION_KEY env var is set")
	}
}

func TestAutoGeneratedKeyFile_CorruptFileGeneratesNew(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	// Write a corrupt key file (wrong length).
	if err := os.WriteFile(tmpKeyFile, []byte("not-valid-hex"), 0600); err != nil {
		t.Fatal(err)
	}
	ResetEncryptionKey()

	// Should still succeed by generating a new key.
	_, err := EncryptToken("test")
	if err != nil {
		t.Fatalf("encrypt with corrupt key file: %v", err)
	}

	// Key file should now be valid.
	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if len(data) != 64 {
		t.Fatalf("expected 64 hex chars after regeneration, got %d", len(data))
	}
}

func TestAutoGeneratedKeyFile_InvalidHex64Bytes(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	// Write a file with exactly 64 bytes but invalid hex characters.
	invalidHex := "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
	if err := os.WriteFile(tmpKeyFile, []byte(invalidHex), 0600); err != nil {
		t.Fatal(err)
	}
	ResetEncryptionKey()

	// Should regenerate and succeed.
	_, err := EncryptToken("test")
	if err != nil {
		t.Fatalf("encrypt with invalid hex key file: %v", err)
	}

	// Key file should now contain valid hex.
	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if len(data) != 64 {
		t.Fatalf("expected 64 hex chars after regeneration, got %d", len(data))
	}
	if _, err := hex.DecodeString(string(data)); err != nil {
		t.Fatalf("regenerated key file is not valid hex: %v", err)
	}
}

func TestAutoGeneratedKeyFile_TrailingNewlineHandled(t *testing.T) {
	tmpDir := t.TempDir()
	tmpKeyFile := filepath.Join(tmpDir, ".encryption_key")

	t.Setenv("ENCRYPTION_KEY", "")
	oldKeyFilePath := keyFilePath
	keyFilePath = tmpKeyFile
	t.Cleanup(func() {
		ResetEncryptionKey()
		keyFilePath = oldKeyFilePath
	})

	// First, generate a valid key file.
	ResetEncryptionKey()
	token := "test-token"
	encrypted, err := EncryptToken(token)
	if err != nil {
		t.Fatalf("initial encrypt: %v", err)
	}

	// Append a trailing newline (as editors often do).
	data, err := os.ReadFile(tmpKeyFile)
	if err != nil {
		t.Fatalf("read key file: %v", err)
	}
	if err := os.WriteFile(tmpKeyFile, append(data, '\n'), 0600); err != nil {
		t.Fatalf("write key file with newline: %v", err)
	}
	ResetEncryptionKey()

	// Should still decrypt correctly — trailing \n is trimmed.
	decrypted, err := DecryptToken(encrypted)
	if err != nil {
		t.Fatalf("decrypt after newline appended: %v", err)
	}
	if decrypted != token {
		t.Errorf("expected %q, got %q", token, decrypted)
	}
}
